import { defineDocs } from "@farming-labs/docs";
import { colorful } from "@farming-labs/theme/colorful";

export default defineDocs({
  entry: "docs",
  theme: colorful(),
  ordering: [
    {
      "slug": "quickstart"
    },
    {
      "slug": "installation"
    },
    {
      "slug": "configuration",
      "children": [
        {
          "slug": "deployment"
        }
      ]
    },
    {
      "slug": "api",
      "children": [
        {
          "slug": "cli",
          "children": [
            {
              "slug": "usage"
            }
          ]
        },
        {
          "slug": "config",
          "children": [
            {
              "slug": "runtime"
            }
          ]
        }
      ]
    },
    {
      "slug": "features",
      "children": [
        {
          "slug": "conversation-memory"
        },
        {
          "slug": "readme-feature-client-server-components"
        },
        {
          "slug": "readme-feature-native-data-state-management"
        }
      ]
    },
    {
      "slug": "architecture",
      "children": [
        {
          "slug": "overview"
        }
      ]
    },
    {
      "slug": "backend",
      "children": [
        {
          "slug": "systems"
        }
      ]
    },
    {
      "slug": "build",
      "children": [
        {
          "slug": "package-structure"
        }
      ]
    },
    {
      "slug": "frontend",
      "children": [
        {
          "slug": "application"
        }
      ]
    }
  ],
  metadata: {
    titleTemplate: "%s – Docs",
    description: "Generated by @farming-labs/docs Cloud",
  },
});
